### ISSUE TITLE
make: *** No rule to make target 'dirs', needed by 'install'.  Stop.

### ISSUE THREAD

**Issue by ilyar** [tonlabs/tonix#10]
I'm read [installation steps](https://github.com/tonlabs/tonix/blob/hier/README.md#installation-steps) and I know stable branch is `hier`
```shell
git clone  git@github.com:tonlabs/tonix.git
cd tonix
git checkout hier
make tools
make install
```
**out**
```shell
make: *** No rule to make target 'dirs', needed by 'install'.  Stop.
```

**Comment by BorisI** [comment]
"dirs" is now a pre-requisite of the default target. Please check out the master branch.
