### ISSUE TITLE
No rule to make target 'tools'

### ISSUE THREAD

**Issue by ilyar** [tonlabs/tonix#9]
```shell
git clone  git@github.com:tonlabs/tonix.git
cd tonix
git checkout hier
make tools
```
**out**
```shell
make: *** No rule to make target 'tools'.  Stop.
```

**Comment by ilyar** [comment]
https://github.com/tonlabs/tonix/commit/34445dbc55ab5e9ec7427e15e8eee0abd44dc9d1

**Comment by BorisI** [comment]
Fixed.

**Comment by ilyar** [comment]
after executing the command `make tools`, it is expected to install the necessary tools, but this does not happen
